modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "ensorcellation"
version = "${file.jarVersion}"
displayName = "Ensorcellation"
updateJSONURL = "https://raw.github.com/cofh/version/main/ensorcellation/update.json"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Adds a multitude of highly configurable Enchantments!

Also improves functionality and flexibility of some vanilla Minecraft Enchantments.

Suitable for both lightly and heavily modded worlds.
'''
[[dependencies.ensorcellation]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ensorcellation]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ensorcellation]]
modId = "cofh_core"
mandatory = true
versionRange = "${cofh_core_version_range}"
ordering = "AFTER"
side = "BOTH"